### ISSUE TITLE
wrong time?

### ISSUE THREAD

**Issue by tukw** [acl-org/acl-2023-miniconf#45]
In both the Schedule and Sessions pages, the start/end time of some sessions seems wrong. For example,

Keynote 1: Geoffrey Hinton: Jul 10, 17:30-18:30 UTC / Invalid date-Invalid date

That time is different from the info in the main website and handbook. And what's "Invalid date-Invalid date"?

There are also many overlaps between sessions in the Schedule page, e.g., keynote 1 overlaps with session 2.

**Comment by EntilZha** [comment]
Hi @tukw, thanks for the bug report. The schedule is fixed in https://github.com/acl-org/acl-2023-miniconf/pull/47 which is live, we have various spreadsheets with even information and one was misparsed as Toronto time as opposed to UTC.

Could you confirm the program looks fine to you?

The invalid-date is a current known bug reported by a few, but I can't reproduce it myself yet. If you have time, providing some more information about your browser/OS/time zone/anything else would be helpful.

**Comment by tukw** [comment]
I confirm that the time of all the sessions is now showing correctly.

I also find that the invalid-date issue only occurs in FireFox, but not in Chrome or Microsoft Edge.
